sudo: required
services:
    - docker

before_install:
    - docker build -t jmor/react-test -f ./client/Dockerfile.dev  ./client

script:
    - docker run jmor/react-test npm test -- --coverage

after_sucess:
    - docker build -t jmor/glorified-fib-client ./client
    - docker build -t jmor/glorified-fib-server ./server
    - docker build -t jmor/glorified-fib-worker ./worker
    - docker build -t jmor/glorified-fib-nginx ./nginx
    #Log in to docker CLI and push images to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jmor/glorified-fib-client
    - docker push jmor/glorified-fib-server
    - docker push jmor/glorified-fib-worker
    - docker push jmor/glorified-fib-nginx
