sudo: required
services:
    - docker

before_install:
    - docker build -t jmor/react-test -f ./client/Dockerfile.dev  ./client

script:
    - docker run -e CI=true jmor/react-test npm test

after_sucess:
    - docker build -t jmor/glorified-fib-client ./client
    - docker build -t jmor/glorified-fib-server ./server
    - docker build -t jmor/glorified-fib-worker ./worker
    - docker build -t jmor/glorified-fib-nginx ./nginx
    #Log in to docker CLI and push images to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jmor/glorified-fib-client
    - docker push jmor/glorified-fib-server
    - docker push jmor/glorified-fib-worker
    - docker push jmor/glorified-fib-nginx

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: glorified-fib 
    env: GlorifiedFib-env
    bucket-name: elasticbeanstalk-us-east-2-640066151654
    bucket-path: glorified-fib
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
